#!/bin/sh /etc/rc.common

START=99
SERVER=WebTunnelAgent
PIDFILE=/var/run/${SERVER}.pid

start () {
    /usr/sbin/$SERVER --daemon --pidfile=$PIDFILE --config=/etc/WebTunnelAgent.properties
}

stop() {
    if [ -f $PIDFILE ] ; then
        kill `cat $PIDFILE`
    fi
}

restart() {
    stop
    sleep 2
    start
}
